cennznet/api.js

packages/api/src/Api.spec.ts
packages/api/src/Api.ts
packages/api/src/ApiRx.ts
packages/api/src/util/getProvider.ts

feat: handle protocol of provider url

---

packages/api/src/Api.ts
packages/api/src/ApiRx.ts
packages/api/src/types.ts
packages/api/src/util/getTimeout.ts
packages/api/test/e2e/api.create.e2e.ts
packages/api/test/e2e/rxapi.create.e2e.ts

feat: reject if the connection fail, add timeout

---

packages/types/src/extrinsic/Extrinsic.spec.ts

fix the unit test error master and #24 are suffering.

fix: CennznetExtrinsic unit test

---

package.json
scripts/adjust.sh

to fix the type definition issue #27

fix: patch ts-ignore in d.ts

---

packages/types/package.json
packages/util/package.json
packages/util/src/index.ts
packages/wallet/package.json
packages/wallet/src/Wallet.spec.ts
packages/wallet/src/index.ts
packages/wallet/src/keyrings/HDKeyring.ts
packages/wallet/src/keyrings/SimpleKeyring.spec.ts
packages/wallet/src/keyrings/SimpleKeyring.ts
yarn.lock

* bump keyring/util/util-crypto version to 0.93.101

fix: move keyring exports to @cennznet/wallet

---

packages/api/src/derives/fees/estimateFee.ts
packages/api/src/derives/index.ts
packages/api/src/types.ts
packages/api/src/util/customDecorators.ts
packages/api/test/e2e/tx.e2e.ts
packages/types/src/extrinsic/Extrinsic.ts
packages/types/src/extrinsic/types.ts
packages/types/src/extrinsic/v1/ExtrinsicSignature.ts
packages/types/src/types.ts

fix ExtrinsicSignature#sign() when feeExchange is set

---

packages/api/src/derives/fees/estimateFee.ts

fix estimateFee by using version bit of version

---

docker-compose.yml
packages/api/src/ApiRx.ts
packages/types/src/injects.ts
yarn.lock

Support CENNZnet node's develop branch

---

docker-compose.yml

Current test coverage is happy with latest cennnet node

Get api.js work with latest cennznet

---

README.md
lerna.json
packages/api/package.json
packages/crml-attestation/package.json
packages/crml-cennzx-spot/package.json
packages/crml-generic-asset/package.json
packages/types/package.json
packages/util/package.json
packages/wallet/package.json

Docker digest: sha256:c33d37c52a6b980ef7e93efbee7383a413616077ecfee9b7e9585d8f834793cd

Release 1.0.1 (cennznet/cennznet:1.0.0)

---

README.md
packages/api/CHANGELOG.md
packages/api/package.json
packages/crml-cennzx-spot/package.json
packages/types/CHANGELOG.md
packages/types/package.json
packages/util/package.json
packages/wallet/CHANGELOG.md
packages/wallet/package.json

Still some things to to do but this is a start
- Update README
- Move release notes to changelogs
- Correct author field

Tidying up

---

packages/api/test/e2e/queries.e2e.ts
packages/api/test/e2e/tx.e2e.ts

- Add genericAsset.updateAssetInfo test
- tx.e2e was getting disorganized so cleaned it up

Tidy up tx.e2e.tests

---

docker-compose.yml
packages/api/package.json
packages/api/src/Api.ts
packages/api/src/types.ts
packages/api/test/e2e/doughnut.e2e.ts
packages/types/src/Doughnut.ts
packages/types/src/extrinsic/types.ts
packages/types/src/types.ts
yarn.lock

The tests works.. for merging we would need new version of doughnut-rs JS lib.. 
For events I get them directly from storage at that block hash cause call back returns me filtered event where event for the doughnut extrinsic is missing. need to investigate more on this.

Added changes for doughnut support

---

packages/types/src/extrinsic/types.spec.ts
packages/types/src/extrinsic/types.ts
yarn.lock

Extrinsic phase on the node side has an additional variant which can create RPC errors decoding certain blocks.

Add initialization to extrinsic phase

---

packages/api/package.json
packages/types/package.json
yarn.lock

Probably related to @trietnguyen267's error

Add @plugnet/doughnut-wasm to deps

---

lerna.json
packages/api/CHANGELOG.md
packages/api/package.json
packages/crml-attestation/package.json
packages/crml-cennzx-spot/package.json
packages/crml-generic-asset/package.json
packages/types/CHANGELOG.md
packages/types/package.json
packages/util/package.json
packages/wallet/package.json

Patch release to fix dependency

Release 1.1.1 (cennznet/cennznet:develop-993900)

---

lerna.json
packages/api/package.json
packages/crml-attestation/package.json
packages/crml-cennzx-spot/package.json
packages/crml-generic-asset/package.json
packages/types/CHANGELOG.md
packages/types/package.json
packages/util/package.json
packages/wallet/package.json

Release 1.1.2 (cennznet/cennznet:develop-993900)

---

packages/api/src/derives/index.ts
packages/api/src/derives/staking/index.ts
packages/api/src/derives/staking/stakingAccount.ts
packages/api/test/e2e/queries.e2e.ts

Added the required modified customise staking query for the task - https://centralitydev.atlassian.net/jira/software/projects/IND/boards/142/backlog?selectedIssue=IND-249
Wanted to add this so that we can include it in the release and I have to available in the UI.

Add derived query for staking accounts

---

jest/initApiPromise.js
packages/api/test/e2e/queries.e2e.ts
packages/types/src/injects.ts
packages/types/src/runtime/ga/BalanceLock.spec.ts
packages/types/src/runtime/ga/BalanceLock.ts
packages/types/src/runtime/ga/WithdrawReasons.spec.ts
packages/types/src/runtime/ga/WithdrawReasons.ts
packages/types/src/runtime/ga/index.ts
packages/types/src/runtime/transaction-payment/TransactionPayment.ts

Closes #131 
Adds:
- BalanceLock and WithdrawReasons types
Changes:
- Applied formatting to some files involved

Fix withdraw reasons decoding

---

packages/api/src/derives/index.ts
packages/api/src/derives/session/index.ts
packages/api/src/derives/session/keyInfo.ts
packages/api/src/derives/staking/index.ts
packages/api/src/derives/staking/stakingAccount.ts
packages/api/test/e2e/queries.e2e.ts

Modified the staking query to be independent of each other. This works well on UI

no coupling between session and account info query for staking

---

lerna.json
packages/api/CHANGELOG.md
packages/api/package.json
packages/crml-attestation/package.json
packages/crml-cennzx-spot/package.json
packages/crml-generic-asset/package.json
packages/types/package.json
packages/util/package.json
packages/wallet/package.json

Patch release to publish working API version on npm

Release 1.2.1 (cennznet/cennznet:develop-993900)

---

packages/api/test/e2e/staking.e2e.ts

updated test

---

.circleci/config.yml

Closes #174 once the NPM_KEY is set for the project.

Add the publish CircleCi job for the release branches

---

package.json

Fix yarn lint command

---

packages/api/test/e2e/staking.e2e.ts

This PR is to address the circle ci build failure on develop branch at https://app.circleci.com/pipelines/github/cennznet/api.js/556/workflows/25421761-6772-4419-a855-0d3baf0955b3/jobs/562
Have updated a staking test.

Fixed a staking test that is failing on develop branch

---

packages/api/src/Api.ts

Polkadot in their newer version changed the way emitter works..
More at https://github.com/polkadot-js/api/blob/cdd6544e20789ec0180dfdecfa60b2a8d379a006/packages/api/src/base/Events.ts#L61
This PR will fix all the timeout related tests

Fix time out emitter issue and all timeout tests

---

packages/api/test/e2e/staking.e2e.ts

The test works fine.. Updated the condition to check if payee's account..

Fix set payout test

---

.circleci/config.yml

npm login step for circle ci config

added login step in circle ci config

---

.circleci/config.yml
lerna.json
packages/api/CHANGELOG.md
packages/api/package.json
packages/types/CHANGELOG.md
packages/types/package.json
packages/util/package.json

1.3.0 alpha.1

---

.circleci/config.yml

Fix [error](https://app.circleci.com/pipelines/github/cennznet/api.js/658/workflows/5698ad35-5cb1-456d-8d13-d17a526b878f/jobs/670) by this PR

Make the old alpha packages deprecated

---

.circleci/config.yml

Fixes [error](https://app.circleci.com/pipelines/github/cennznet/api.js/662/workflows/aeb70e23-9546-45cc-b40c-cca41c12fbb7/jobs/676)

Fix deprecated package syntax

---

.circleci/config.yml
lerna.json
packages/api/package.json
packages/types/package.json
packages/util/package.json

This will add the required source file to npm registry for pre-release version (alpha).
Also bumped the new alpha version..

Added yarn build before publish and bump alpha version

---

docs/examples/promise/01_simple_connect/index.js
docs/examples/promise/03_listen_to_balance_change/index.js
docs/examples/promise/04_listen_to_multiple_balances_change/index.js
docs/examples/promise/06_make_transfer/index.js
docs/examples/promise/08_read_storage_at/index.js
docs/examples/promise/09_make_transfer_with_allowed_block_permissions_only/index.js
docs/examples/promise/11_transfer_events/index.js
docs/examples/promise/12_chose_fee_asset_to_pay_tx_fee/index.js
docs/examples/rx/03_listen_to_balance_change/index.js
docs/examples/rx/05_read_storage/index.js
docs/examples/rx/06_make_transfer/index.js
docs/examples/rx/08_transfer_events/index.js
docs/examples/rx/09_chose_fee_asset_to_pay_tx_fee/index.js

This PR fixes the docs example where transactionPayment option is used.. earlier the example worked, but the fees were not used from the fee asset (in this case CENNZ)..

Fixed fee asset example while sending extrinsic

---

packages/api/test/e2e/api.calls.e2e.ts
packages/types/src/interfaces/augment-types.ts
packages/types/src/interfaces/injects.ts
packages/types/src/interfaces/system/definitions.ts
packages/types/src/interfaces/system/types.ts

Added types to support rv36 events.
Closes https://github.com/cennznet/api.js/issues/221

Fix event decoding with rv 36

---

docs/examples/promise/01_simple_connect/package.json
docs/examples/promise/02_listen_to_blocks/package.json
docs/examples/promise/03_listen_to_balance_change/package.json
docs/examples/promise/04_listen_to_multiple_balances_change/package.json
docs/examples/promise/05_unsubscribe/package.json
docs/examples/promise/06_make_transfer/package.json
docs/examples/promise/07_read_storage/package.json
docs/examples/promise/08_read_storage_at/package.json
docs/examples/promise/09_make_transfer_with_allowed_block_permissions_only/package.json
docs/examples/promise/10_system_events/package.json
docs/examples/promise/11_transfer_events/package.json
docs/examples/promise/12_chose_fee_asset_to_pay_tx_fee/package.json
docs/examples/rx/01_simple_connect/package.json
docs/examples/rx/02_listen_to_blocks/package.json
docs/examples/rx/03_listen_to_balance_change/package.json
docs/examples/rx/04_unsubscribe/package.json
docs/examples/rx/05_read_storage/package.json
docs/examples/rx/06_make_transfer/package.json
docs/examples/rx/07_system_events/package.json
docs/examples/rx/08_transfer_events/package.json
docs/examples/rx/09_chose_fee_asset_to_pay_tx_fee/package.json
lerna.json
packages/api/CHANGELOG.md
packages/api/package.json
packages/types/package.json
packages/util/package.json

Pre release branch for CENNZnet API to release 1.3.2 version.
closes #241

Pre release branch for CENNZnet API to release 1.3.2 version.

---

docs/cennznet/errors.md
docs/cennznet/events.md
docs/cennznet/extrinsics.md
docs/cennznet/rpc.md
docs/cennznet/storage.md
lerna.json
packages/api/CHANGELOG.md
packages/api/package.json
packages/types/CHANGELOG.md
packages/types/package.json
packages/util/package.json

Pre-release 1.3.3 alpha.1(cennznet/cennznet:develop-4ff509)

Prerelease/1.3.3 alpha.1

---

docs/examples/promise/13_batch_all_transfer/package.json
lerna.json
packages/api/CHANGELOG.md
packages/api/package.json
packages/types/CHANGELOG.md
packages/types/package.json
packages/util/package.json

alpha release with NFT support

Prep 1.3.5-alpha.0 release

---

.github/workflows/ci.yml
docker-compose.yml
packages/api/test/e2e/api.calls.e2e.ts
packages/api/test/e2e/api.v36-compat.e2e.ts

Remove the dependency on the external archive node

Refactor v36 compatibility tests

---

.github/workflows/publish.yml
babel.config.js
package.json
packages/api/README.md
packages/api/package.json
packages/api/src/Api.ts
packages/api/test/e2e/util/SingleAccountSigner.ts
packages/types/src/types.ts
packages/util/src/types.ts
scripts/build-release.sh
tsconfig.json
yarn.lock

Update release build

---

.github/workflows/publish.yml

Retry 1.3.5-alpha.1 release

---

.github/workflows/ci.yml
packages/api/src/derives/nft/balanceOf.ts
packages/api/test/e2e/api.create.e2e.ts
packages/api/test/e2e/nft.e2e.ts

1.x release with latest metadata + tests

Prerelease/1.4.0 alpha.0

---

packages/api/src/derives/index.ts
packages/api/src/derives/staking/index.ts
packages/api/src/derives/staking/query.ts
packages/api/src/derives/staking/types.ts
packages/api/src/derives/staking/waitingInfo.ts
packages/api/test/e2e/staking.e2e.ts

Fixed staking derive queries and added tests.
Closes https://github.com/cennznet/api.js/issues/273

Test for derived staking query

---

packages/api/src/derives/nft/index.ts
packages/api/src/derives/nft/tokenInfo.ts
packages/api/src/derives/nft/tokenInfoForCollection.ts
packages/api/src/derives/nft/types.ts
packages/api/test/e2e/nft.e2e.ts

Tried a way to write derived query..

Derive query with all the details for tokens in a collection

---

docs/examples/promise/01_simple_connect/package.json
docs/examples/promise/02_listen_to_blocks/package.json
docs/examples/promise/03_listen_to_balance_change/package.json
docs/examples/promise/04_listen_to_multiple_balances_change/package.json
docs/examples/promise/05_unsubscribe/package.json
docs/examples/promise/06_make_transfer/package.json
docs/examples/promise/07_read_storage/package.json
docs/examples/promise/08_read_storage_at/package.json
docs/examples/promise/09_make_transfer_with_allowed_block_permissions_only/package.json
docs/examples/promise/10_system_events/package.json
docs/examples/promise/11_transfer_events/package.json
docs/examples/promise/12_chose_fee_asset_to_pay_tx_fee/package.json
docs/examples/promise/13_batch_all_transfer/package.json
docs/examples/rx/01_simple_connect/package.json
docs/examples/rx/02_listen_to_blocks/package.json
docs/examples/rx/03_listen_to_balance_change/package.json
docs/examples/rx/04_unsubscribe/package.json
docs/examples/rx/05_read_storage/package.json
docs/examples/rx/06_make_transfer/package.json
docs/examples/rx/07_system_events/package.json
docs/examples/rx/08_transfer_events/package.json
docs/examples/rx/09_chose_fee_asset_to_pay_tx_fee/package.json
lerna.json
packages/api/CHANGELOG.md
packages/api/package.json
packages/types/CHANGELOG.md
packages/types/package.json
packages/util/package.json
test/package.json

Just bump packages + update changelogs

Prepare 1.4.0 release

---

jest/integration.config.js
packages/api/src/derives/fees/estimateFee.ts
packages/api/src/derives/types.ts
packages/api/test/e2e/tx.e2e.ts
packages/types/src/interfaces/extrinsic/index.ts
packages/types/src/interfaces/extrinsic/v1/Extrinsic.ts
packages/types/src/interfaces/injects.ts

continuation of the PR to develop branch:
https://github.com/cennznet/api.js/pull/316

Improve tx payment_interface(#244)

---

packages/api/src/derives/nft/index.ts
packages/api/src/derives/nft/openCollectionListings.ts
packages/api/src/derives/nft/types.ts
packages/api/test/e2e/nft.e2e.ts

Derived query for retrieving all tokens that have an open listings with the given collection ID. closes #320

Nft open listings (#320)

---

docs/examples/promise/02.1_listen_to_blocks_api_combineLatest/README.md
docs/examples/promise/02.1_listen_to_blocks_api_combineLatest/index.js
docs/examples/promise/02.1_listen_to_blocks_api_combineLatest/package.json

Good example to have it in repo for anyone who wants keep on subscription of few query when new block is added

added example to use api with combineLatest to query different attributes

---

.github/workflows/ci.yml
docker-compose.yml
packages/api/src/derives/cennzx/cennzxTrade.e2e.ts
packages/api/src/derives/fees/estimateFee.ts
packages/api/test/e2e/cennzx.e2e.ts
packages/types/src/interfaces/augment-types.ts
packages/types/src/interfaces/cennzx/definitions.ts
packages/types/src/interfaces/cennzx/types.ts

With this PR - CENNZX can support asset with 18 dp balance...
Using node at https://github.com/cennznet/cennznet/pull/456

Fix types for cennzx to support 18dp balance

---

docs/cennznet/cennzx.md
docs/cennznet/genericAsset.md
docs/cennznet/nft.md
docs/cennznet/rpc.md
docs/cennznet/staking.md
scripts/MetadataMd.ts

Closes https://github.com/cennznet/api.js/issues/309

Module specific mark down file

---

packages/api/src/Api.ts
packages/api/src/ApiRx.ts
packages/api/src/types.ts
packages/api/src/util/getProvider.ts
packages/api/test/e2e/api.create.e2e.ts
packages/api/test/e2e/rxapi.create.e2e.ts

updated with option to connect via network name

---

packages/types/src/interfaces/injects.ts

Add LookupSource type definition

---

lerna.json
packages/api/CHANGELOG.md
packages/api/package.json
packages/types/CHANGELOG.md
packages/types/package.json
packages/util/package.json

Releasing 1.5.0-alpha.0 version

Prerelease/1.5.0 alpha.0

---

.github/workflows/ci.yml
packages/api/src/derives/ethBridge/eventProof.ts
packages/api/src/derives/ethBridge/types.ts
packages/api/src/derives/index.ts
packages/api/src/derives/nft/tokenInfoForCollection.ts
packages/api/src/derives/nft/types.ts
packages/api/src/derives/types.ts
packages/api/test/e2e/cennzx.e2e.ts
packages/api/test/e2e/ethBridge.e2e.ts
packages/api/test/e2e/nft.e2e.ts
packages/types/src/interfaces/ethy/definitions.ts
packages/types/src/interfaces/ethy/types.ts
scripts/generateSlimMetadata.ts

Fixes ts error when using derived query..
Updated Ethy (event proof) call

Fix derive type

---

packages/api/src/derives/ethBridge/eventProof.ts
packages/api/test/e2e/ethBridge.e2e.ts
packages/types/package.json
packages/types/scripts/fixTypeDefWrapper.js
packages/types/src/index.ts
packages/types/src/interfaces/augment-api-query.ts
packages/types/src/interfaces/augment-api-tx.ts
packages/types/src/interfaces/types.ts

Temporary fixes https://github.com/cennznet/api.js/issues/403
we will revert this change once https://github.com/cennznet/cennznet/issues/542 is solved

Fix definition with camel case storage for example seriesMetadataURI

---

docker-compose.yml
packages/api/package.json
packages/api/src/derives/ethBridge/eventProof.ts
packages/api/src/derives/ethBridge/types.ts
yarn.lock

With this PR, the derived proof is in ready to use format with validator set.
can be used in
1. withdraw
2. set validators

add validators set to event proof to make it ready to use

---

packages/api/src/derives/nft/openCollectionListings.ts
packages/signer-cli/package.json
packages/types/package.json
yarn.lock

https://github.com/cennznet/api.js/pull/427
Fixing bug in derive query for open listing

Fixing open listing on develop branch as well

---

packages/api/README.md

Update installation instructions from using npm to yarn as the npm way results in errors

Update installation instructions in README

---

lerna.json
packages/api/CHANGELOG.md
packages/api/package.json
packages/signer-cli/package.json
packages/types/CHANGELOG.md
packages/types/package.json

Prerelease/2.1.0 alpha.2

---

packages/api/src/derives/nft/collectionInfo.ts
packages/api/src/derives/nft/index.ts
packages/api/src/derives/nft/openCollectionListings.ts
packages/api/src/derives/nft/tokenInfo.ts
packages/api/src/derives/nft/types.ts
packages/api/src/util/getProvider.ts
packages/api/test/e2e/api.create.e2e.ts
packages/api/test/e2e/ethBridge.e2e.ts
packages/api/test/e2e/nft.e2e.ts

This PR is to audit usage of toHuman calls, as it can sometimes cause issue.

audit toHuman usage in the api

---

lerna.json
packages/api/CHANGELOG.md
packages/api/package.json
packages/signer-cli/package.json
packages/types/CHANGELOG.md
packages/types/package.json

Description - This PR is to create a release version 2.1.0-rc.1 on npm registry.
Files changed
- learn.json
- [api|types]/changelog
- [api|types|signer-cli]/package.json

release 2.1.0-rc.1 version

---

lerna.json
packages/api/CHANGELOG.md
packages/api/package.json
packages/signer-cli/package.json
packages/types/CHANGELOG.md
packages/types/package.json

Description - This PR is to create a release version 2.1.0-rc.2 on npm registry.
Files changed
learn.json
[api|types]/changelog
[api|types|signer-cli]/package.json

release 2.1.0-rc.2 version

---

lerna.json
packages/api/package.json
packages/signer-cli/package.json
packages/types/CHANGELOG.md
packages/types/package.json

Releasing version 2.1.0-rc.3 on npm

Release version 2.1.0-rc.3

---

lerna.json
packages/api/package.json
packages/signer-cli/package.json
packages/types/CHANGELOG.md
packages/types/package.json

Prerelease version 2.1.0-rc.4
