packages/api/src/util/getProvider.spec.ts

This PR ensures that:
* Unit tests do not instantiate real `HttpProvider`'s or `WsProvider`'s.
* Unit tests live closer to the SUT.

`getProvider()` Unit Tests

---

packages/api/src/Api.ts
packages/api/src/ApiRx.ts

This PR ensures that:
* `genericAsset` is typed as `GenericAsset`, as opposed to `GenericAsset | undefined`.
* `cennzxSpot` is typed as `CennzxSpot`, as opposed to `CennzxSpot | undefined`.
* Consumers of this API, using TypeScript, do not need to add unnecessary guards if they have instantiated an instance of `Api` by `await`'ing a call to `Api.create()`.

Plugin Injection

---

packages/crml-attestation/package.json

A missing piece should be done when I put crml-attestation into this repo.

fix: change peerDependencies to dependencies in crml-attestation/package.json

---

docker-compose.yml

Its better to ensure api.js work with a specific tag/version of cennznet node whenever we release, as we are not able to ensure api always work with the latest cennznet.

Fix cennznet docker image version

---

packages/types/src/runtime/sylo/index.ts

When fetching values from substrate which had the types `PreKeyBundle` or `WithdrawnPreKeyBundle`, the values were decoding into empty bytes arrays, i.e `0x`. The types were simple, and removing the unnecessary constructor lines seemed to fix this issue.

Fix Sylo Runtime Types

---

packages/types/src/runtime/sylo/index.ts

As part of Sylo module audit, we introduced Message and MessageId types (https://github.com/cennznet/cennznet/pull/180)

Add missing types for Sylo

---

.circleci/config.yml
babel.config.js
package.json
yarn.lock

While making a release with recent changes had this issue on Jenkins pipeline and build failed
Browserslist: caniuse-lite is outdated. Please run the following command: `yarn upgrade`
{ SyntaxError: /workdir/packages/types/src/runtime/ga/WithdrawReasons.ts: Identifier directly after number (20:29)
18 | const ReasonMask = {
19 |   /// In order to pay for (system) transaction costs.
> 20 |   TRANSACTION_PAYMENT: 0b0000_0001,
|                              ^
21 |   /// In order to transfer ownership.
22 |   TRANSFER: 0b0000_0010,
23 |   /// In order to reserve some funds for a later return or repatriation.
at Object.raise (/workdir/node_modules/@babel/parser/lib/index.js:7017:17)
at Object.readRadixNumber (/workdir/node_modules/@babel/parser/lib/index.js:7876:18)
at Object.getTokenFromCode …

Support underscore in number with babel plugin

---

.eslintrc.js
package.json
yarn.lock

Extended 
1. eslint:recommended
2. plugin:@typescript-eslint/recommended
3. plugin:@typescript-eslint/recommended-requiring-type-checking
Had to add required packages to use it
yarn add -D eslint typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin
Disable few specific type checks. 
"@typescript-eslint/explicit-module-boundary-types": "off",
"@typescript-eslint/no-explicit-any": "off",
"@typescript-eslint/no-var-requires": "off",
"@typescript-eslint/no-unused-vars": "off",
"@typescript-eslint/ban-ts-comment": "off",
"@typescript-eslint/ban-types": "off",
"@typescript-eslint/no-inferrable-types": "off"
Turned off few more rules to support this
Can enable these one by one once we merge this to base branch (chore/convert_tslint_to_eslint)

extend eslintrc with recommended typescript-eslint

---

.eslintrc.js
packages/util/src/unit/parseUnits.ts

PR - To solve the rules either commented or set OFF.
This one is to enable the support for "prefer-const".
The file changed get auto-indentate..tried to update the formatting to what it was earlier but commit will auto format it with command - pretty-quick --staged --pattern 'packages/**/src/**/*'
"husky": {
"hooks": {
"pre-commit": "pretty-quick --staged --pattern 'packages/**/src/**/*' && npx eslint . --ext .ts"
}
},
If required I can remove pretty-quick and push the changes again

Chore tslint/enable prefer const rule

---

.circleci/config.yml

Now that linting errors have been turned off in https://github.com/cennznet/api.js/pull/160/ , I suppose this easy fix could be merged with linting fix now.
https://app.circleci.com/pipelines/github/cennznet/api.js/491/workflows/4386c9e3-8f2c-4793-841f-17cf8f3ecce7/jobs/493

Enable linting on CircleCI

---

.eslintrc.js
package.json
yarn.lock

PR - Enable "import/order" rule..
Had to add dependency 
**yarn add -D -W eslint-plugin-import**
and update the eslintrc.js to use import
"plugins": [
"@typescript-eslint",
'import',
],

Enable "import/order" rule

---

.eslintrc.js
packages/api/src/Api.ts
packages/api/src/ApiRx.ts
packages/api/src/types.ts
packages/api/src/util/getTimeout.ts
packages/api/test/e2e/rxapi.create.e2e.ts

Eventemitter was internal to ProviderInterface and programming towards the internal was wrong in the first place. Later Polkadot changed that internal private part and introduced "on" method for handling the error.

Fix rxapi.queries.e2e.ts

---

packages/api/src/ApiRx.ts

Maintain the behaviour strictly as it used to be. During connection setup, there is an opportunity window for a disconnect to be useful between when a connection is made successfully and when the API is "ready".

Maintain the behaviour of ApiRx connection establishment

---

.circleci/config.yml
docker-compose.yml
packages/api/src/Api.ts
packages/api/src/ApiRx.ts
packages/api/test/e2e/api.calls.e2e.ts
packages/types/src/interfaces/augment-types.ts
packages/types/src/interfaces/extrinsic/index.ts
packages/types/src/interfaces/extrinsic/types.ts
packages/types/src/interfaces/extrinsic/v0/ExtrinsicPayloadV0.ts
packages/types/src/interfaces/extrinsic/v0/ExtrinsicSignatureV0.ts
packages/types/src/interfaces/injects.ts
packages/types/src/interfaces/sylo/v0/index.ts
packages/types/src/interfaces/system/definitions.ts
packages/types/src/interfaces/system/types.ts

This PR is to address the issue decoding the blocks running on Azalea which supports old types (Extrinsic Signature). The fix was inspired by the way it was handled in https://github.com/polkadot-js/api/issues/2723
With typesBundle we can now let the API know which type definition to use for what version
I have tested it for some blocks on Azalea which had GA as well as Sylo extrinsic.. It decodes well.. Also tried to use send an extrinsic on v37 and tried to see if the block decodes well..

support decoding of old block and current block on V37 chain

---

config/index.js
docker-compose.yml
packages/api/src/derives/balances.ts
packages/api/src/derives/index.ts
packages/api/src/derives/types.ts
packages/api/test/e2e/api.calls.e2e.ts
packages/api/test/e2e/api.v36-compat.e2e.ts

band-aid fix for testing v36 backwards compatibility.
In future would be nice to run the API object through the entire suite for each different node/runtime version
Have added balances derived query to keep the code base backward compatible..

Add a minimal test suite for v36 backwards compatibility

---

packages/api/package.json

@cennznet/util - is been used in https://github.com/cennznet/api.js/blob/674f3e22fa9dd4ff5a044d8127dc0c7628eeef1a/packages/api/src/derives/cennzx/utils/index.ts
Discovered this issue while using the new version in uncover project..
The reason for this issue is earlier @cennnznet/types had this dependencies.. But when we moved types generation in @cennznet/types.... we removed this dependency cause that was not required for @cennznet/types project.

Fix dependencies in API package

---

.github/workflows/publish.yml

Corrected regex further...
The earlier one yielded - **version 1.3.3-alpha.1**
However we required 1.3.3-alpha.1
https://github.com/cennznet/api.js/runs/1923210924?check_suite_focus=true
Updated regex and tested locally
cat packages/api/package.json         | grep version         | head -1         | grep -E -o '[0-9|.]+\-*[a-z]*\.[0-9]+|]+'
tested with version **1.3.3** and **1.3.3-alpha.1**

Prerelease/1.3.3 alpha.1

---

packages/api/test/e2e/api.create.e2e.ts
packages/api/test/e2e/tx.e2e.ts
packages/api/test/e2e/util/SingleAccountSigner.ts
packages/types/src/interfaces/extrinsic/SignerPayload.ts
packages/types/src/interfaces/extrinsic/index.ts
packages/types/src/interfaces/injects.ts

Creating ExtrinsicPayload via api.registry should provide the payload object with transactionPayment option.

Added extrinsicPayload in registry

---

.eslintrc.js
package.json
packages/api/src/derives/staking/electedInfo.ts
packages/api/src/derives/staking/index.ts
packages/api/src/derives/staking/overview.ts
packages/api/src/derives/staking/query.ts
packages/api/src/derives/staking/stashes.ts
packages/api/src/derives/staking/types.ts
packages/api/src/derives/staking/validators.ts
packages/api/src/derives/staking/waitingInfo.ts
yarn.lock

Earlier the derived queries were added in UI project... With this PR, the api will be decorated with proper derived queries which are used in UI. 
Few things to mention..
1. Updated eslint rule for duplicate import  - 
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md updated the duplicate import rule as we now have 
import type {xyz} from 'abc';
import {def} from 'abc'; 
false positive rule on import type - https://github.com/typescript-eslint/typescript-eslint/issues/2315
2. Updated prettier to latest version to support typescript 3.8 syntax (for example import type) 
https://github.com/prettier/prettier/issues/7263
3. For the new staking derived queries added, needed to add // @ts-ignore at few places as in parent (polkadot) same call is used …

Copied staking derived queries from UI project

---

.gitignore
docs/cennznet/attestation.md
docs/cennznet/cennzx.md
docs/cennznet/nft.md
docs/cennznet/staking.md
docs/interfaces/nft_types.collectioninfo.md
docs/interfaces/nft_types.derivetokeninfo.md
docs/interfaces/staking_types.derivestakingelected.md
docs/interfaces/staking_types.derivestakingoverview.md
docs/interfaces/staking_types.derivestakingquery.md
docs/interfaces/staking_types.derivestakingstash.md
docs/interfaces/types.derivebalancesaccount.md
docs/interfaces/types.derivedsessionkeyinfo.md
docs/interfaces/types.derivedstakinginfo.md
docs/interfaces/types.estimatefeeparams.md
docs/interfaces/types.paymentoptions.md
package.json
scripts/MetadataMd.ts
yarn.lock

Used typedoc to generate typescript doc for derive and merged the generated doc with the module..
https://github.com/cennznet/api.js/blob/deriveDocs/docs/cennznet/nft.md
https://github.com/cennznet/api.js/blob/deriveDocs/docs/cennznet/cennzx.md
https://github.com/cennznet/api.js/blob/deriveDocs/docs/cennznet/staking.md
also add the interface to doc folder so that when user navigates thro' link in the document, it know what interface is used..

Doc generated from typedoc for derive

---

package.json
yarn.lock

Fixes - https://github.com/cennznet/api.js/security/dependabot

Dependabot alert

---

.github/workflows/publish-stable.yml

GitHub Actions run in parallel.  From the last release pipeline https://github.com/cennznet/api.js/runs/3157338208?check_suite_focus=true
merge-release-branch completes before generate-metadata-for-extension...
generate-metadata-for-extension fails because there is nothing to commit, no new files to commit.
With this PR, committing the extension data to master in GitHub Actions

Commit extension data to master branch

---

packages/api/src/util/helper.ts
packages/api/test/e2e/ethBridge.e2e.ts

While testing on rata, figured out that the notary keys are
```
[
'0xf88bc2c5918b40a8aa1905f3fc5e4b90b2a3142c',
'0x478adb7a82be57337f433c6e515ee817b45d936e',
'0x7d0f662f04ac77fdc1c8e51da2f9aea7c1aabc7f',
'0x360bf1d9d6319afbbb678dea92842b76c3b4f3a9',
'0xb94719a6a34656f76002590a52ef4d2e8a29c7ec'
]
```
and signatures in event proof comes as
```
[
"0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
"0xb209b017eba3a753f6bf56b440d901065f99e18de0de1fc65186050b44a0531d5fdbcbf7d7f87b8ed389cc9c27a79085afd681a7517fa8260c95c5dd9d0d09c200",
"0x73be4d71e2bde9ee902e8c6e6e04418d39665e14551897e61dd41f559f3103747f4123876a94dfbfd741ce6bfaae909c912d43ad5279de23da969124894fc1f900", …
```

fix the extract eth signature and convert it to r,s,v part

---

packages/api/package.json

Might close https://github.com/cennznet/api.js/issues/390
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
Not sure, why it was changed in commit - https://github.com/cennznet/api.js/commit/e402c838a0715f935e70d51a70fe6ee614f3026f

fix issue with bundler

---

packages/types/src/interfaces/injects.ts

Description- for runtime at which azalea currently is, Key type should be '(AccountId, AccountId, AccountId, AccountId, BeefyKey)'
Donno if we want to spin a dev node on 2.0.0 in ci and have test against that.

for rtm < 47, use specific session key

---

packages/api/CHANGELOG.md
packages/api/README.md
packages/api/test/e2e/api.create.e2e.ts
packages/types/src/interfaces/injects.ts

Desc - Currently the balance lock query for generic asset fails with rc3.. This PR fixes that. Also added link to upgrade guide so that it appears on npm registry.
File changed - 
packages/api/CHANGELOG.md
packages/api/README.md
packages/api/test/e2e/api.create.e2e.ts (added test)
packages/types/src/interfaces/injects.ts - use specific Reasons type

Fixes lock balance for rtm version <= 48
